export const langs = {
    main: {
        cz: [
            'Přispějte',
            'Leleka – nadační fond',
            'Každý má svou frontu ',
            'KDO MY JSME',
            'Mezinárodní nadační fond Leleka byl založen Ukrajinci z Karlových Varů a jeho cílem je pomáhat těm, kteří chrání Ukrajinu před agresorem, stejně jako těm, kteří byli nuceni se přestěhovat do Česka.',
            'Válka přišla na Ukrajinu iž v roce 2014, kdy první ruští vojáci a žoldáci obsadili města našeho rodného Donbasu. Ne z televizních zpráv a internetu jsme se museli dozvědět, co se dělo v Doněcku, protože jsme viděli všechno na vlastní oči. Po přestěhování do České republiky jsme svými silami pokračovali v pomoci našim bojovníkům v zóně OSS. Od 24. února začala naše skupina jednat koordinovaněji. Za dva měsíce jsme byli schopni poskytnout mnoha vojákům Ozbrojených sil Ukrajiny a dobrovolníkům lékárničky, neprůstřelné vesty a další předměty individuální ochrany. Do nemocnic Dněpra a Charkova byly převezeny potřebné léky. ',
            'A pak přišel čas založit nadační fond, který by spojil úsilí mnoha lidí a organizací. Musime se sjednotit kvůli vítězství, aby na Ukrajině znovu zavládl mír.',
            'Chceš pomocí',
            'Jsi člověk, nebo organizace, která má humanitární a lékařské zdroje',
            'Potřebuješ pomoc',
            'Jsi člověk, nebo organizace, která potřebuje humanitární a lékařské zdroje',
            'Naše činnost',
            '1. Nakupujeme po celé Evropě a posíláme na Ukrajnu všechno, co je nezbytné nutné pro naše obránce:',
            'deficitné optické vybavení, zejména termovize, přístrojе nočního vidění a další',
            'léky a zdravotnické prostředky první potřeby při zraněních',
            'osobní ochranné prostředky (záchranné neprůstřelné vesty, chrániče kolen, brýle a sluchátka), lékárničky a vojenské oblečení ',
            '2. Pomáháme nuceným přistěhovalcům z Ukrajiny do Česka: ',
            's ubytováním a integraci',
            's umístěním dětí do sportovních sekcí ',
            's organizací dětského volného času ',
            'humanitární pomocí (věci, obuv, nádobí, nábytek a zařízení do bytů, dětské kočárky, hráčky atd.) spolu se spolkem Nádech z.s. v Karlových Varech',
            'Více detailní informací na našich sociálních sítích',
            'Finanční pomoc na sběr zdrojů',
            'Za finanční dary Leleka nakupuje dostupné zdroje a dodává Ukrajincům podle potřeby',
            'Rekvizity',
            'Sledujte nejnovější zprávy:'
        ],
        en: [
            'Donate',
            'Leleka - charity fund',
            'Everyone fights on their own front',
            'WHO WE ARE',
            'Charity fund “Leleka” is founded by Ukrainians from Karlovy Vary, and is intended to help those who defend Ukraine from the aggressor and those who were forced to move to Czech Republic.',
            'The war came to our homeland in 2014, when first Russian soldiers and mercenaries invaded cities of our home Donbas region. We had to find out everything that happened in Donetsk not from the television news or the internet - we have seen everything firsthand. Already living in Czech Republic we continued to help our military in the Joint Forces Operation zone. Since 24 of February our group began to make more coordinated actions. In two months we succeeded in providing many of the soldiers from the Armed Forces of Ukraine and volunteers with medical packs, bulletproof vests and other personal protection equipment. Hospitals in Dnipro and Kharkiv were supplied with necessary medicine.',
            'Now it is time to launch a charity fund to unite the efforts of many people and organisations. To unite for the victory, to bring peace to Ukraine. ',
            'I want to help ',
            'You are the person or organisation that has in stock humanitarian and medical resources.',
            'I need help',
            'You are the person or organisation that needs humanitarian and medical resources. ',
            'WHAT DO WE DO?',
            '1. We buy everything that our defenders need throughout all Europe and send to Ukraine:',
            'scarce optical equipment such as thermal imagers, night-vision devices, etc; ',
            'medicine and essential medical supplies for injury;',
            'personal protection equipment (bulletproof vests, knee pads, military goggles and headphones), medical packs and military fatigues;',
            'We help Ukrainian refugees in Czech Republic:',
            'with accommodation;',
            'with enrolling children in sports clubs;',
            'organisation of children’s activities;',
            'humanitarian help (clothes, shoes, etc);',
            'More detailed information is in our social media',
            'Financial assistance for collection of the resources',
            'For the money transferred Leleka buys available resources and supply to Ukrainians when needed',
            'Bank transfer details',
            'Follow the latest news:'
        ],
        ua: [
            'Допомогти',
            'Leleka - Благодійний фонд',
            'У кожного свій фронт',
            'Хто ми',
            'Благодійний фонд "Лелека" заснований українцями з Карлових Вар і має на меті допомагати тим, хто захищає Україну від агресора, а також тим, хто були вимушені переїхати до Чехії.',
            'Війна прийшла в наш дім ще 2014 року, коли перші російські військові та найманці захопили міста нашого рідного Донбасу. Не з телевізійних новин та інтернету нам довелося дізнатися, що відбувалося в Донецьку, адже бачили все на власні очі. Вже живучи у Чехії, ми своїми силами продовжували допомагати нашим бійцям в зоні ООС. З 24 лютого наша група почала діяти більш скоординовано. За 2 місяці ми змогли забезпечити багатьох військових ЗСУ і добровольців аптечками, бронежилетами та іншими предметами індивідуального захисту. До шпиталів Дніпра та Харкова були передані необхідні ліки.',
            'Настав час створити благодійний фонд, аби об\'єднати зусилля багатьох людей і організацій. Об\'єднати заради перемоги, заради того, аби в Україні знову запанував мир.',
            'Хочу допомогти',
            'Ти людина, чи організація яка і має в наявності гуманітарні та медичні ресурси.',
            'Необхідна допомога',
            'Ти людина, чи організація якій необхідна гуманітарні та медичні ресурси.',
            'Що ми робимо',
            '1. Закуповуємо по всій Європі та відправляємо в Україну все те, що так необхідне нашим захисникам:',
            'дефіцитне оптичне обладнання, таке як тепловізори, прибори нічного бачення тощо',
            'ліки та медичні засоби першої необхідності при пораненнях',
            'засоби індивідуального захисту (бронежилети, наколінники, окуляри та навушники), аптечки та військовий одяг',
            '2. Допомагаємо вимушеним переселенцям з України до Чехії:',
            'з поселенням',
            'з влаштуванням дітей до спортивних секцій',
            'з організацією дитячого дозвілля',
            'гуманітарною допомогою (речі, взуття тощо)',
            'Більше детальної інформації у наших соціальних мережах',
            'Фінансова допомога на збір ресурсів',
            'За переказані кошти Leleka закуповує доступні ресурси та постачає українцям у потребі.',
            'Реквізити',
            'Слідкуйте за останніми новинами:'
        ]
    },
    transfer: {
        cz: [
            'Informace pro fyzické osoby',
            'Vážení, nepochybujte o tom, že každý váš příspěvek do fondu výrazně pomůže naší společné velké věci! Především vaše podpora znamená boj za mír, demokracii a solidaritu a hlavně mír pro Ukrajinu a celý civilizovaný svět. Každý z nás může hodně, ale společně můžeme všechno!',
            'Informace pro právnické osoby',
            'Vážení podnikatelé, každý váš finanční příspěvek pomůže těm, kteří potřebují pomoc a podporu, kteří stojí za ochranou míru a demokracie v Evropě a jsou garanty naší svobodné budoucnosti. Za charitativní finanční výlohy české legislativy počítá s daňovými úlevami. Pro sponzorské společnosti máme připravenou smlouvu, která je stanovena zákonem při charitativním příspěvku na konkrétní účelovou pomoc. Podporováním naší charitativní nadace podporujete naši svobodu!',
            'Rekvizity | Leleka – nadační fond'
        ],
        en: [
            'Information for Natural persons',
            'Be sure that each of your contribution to the fund will help a lot in our common great goal! First of all, your support means the fight for peace, democracy and solidarity, and above all - peace for Ukraine and all civilised world. Everyone can do a lot, but together we can do everything!',
            'Information for Juridical persons ',
            'Dear entrepreneurs, each of your financial contributions will help those who need assistance and support, those who stand up for peace and democracy in Europe and are the guarantees of our free future. For the charitable financial contributions due to the Czech legislation there are tax benefits. For the company-sponsor we have prepared an agreement  provided by law when making a charitable contribution for the specific targeted assistance. By supporting our charity fund you support our freedom!',
            'Bank transfer details | Leleka - charity fund'
        ],
        ua: [
            'Інформація для фізичних осіб',
            'Шановні, не майте сумнiв, що кожний ваш посильний внесок у фонд, значно допоможе нашiй спiльнiй великiй справi! Насамперед , ваша пiдтримка означає боротьбу за мир, демократiю i солiдарнiсть, та головне - мир для Украïни та всього цивiлiзованого світу. Кожен із нас може багато, але разом ми можемо все!',
            'Інформація для підприємств',
            'Шановні підприємці, кожен ваш фінансовий внесок допоможе тим, хто потребує допомоги та підтримки, хто стоїть на захисті миру та демократії в Європі та є гарантами нашого вільного майбутнього. За благодійні фінансові винесення Чеським законодавством передбачено податкові пільги. Для компаній-спонсорів у нас підготовлений договір, який передбачений законом при внесенні благодійного внеску на конкретну цільову допомогу. Підтримуючи наш благодійний фонд, ви підтримуєте нашу свободу!',
            'Реквізити | Leleka - Благодійний фонд'
        ],
    },
    need_resources: {
        cz: [
            'Potřebuji zdroje',
            'Osobní data',
            'Příjmení',
            'Jméno',
            'По батькові',
            'Typ průkazů',
            'Číslo průkazů',
            'Vyberte typ',
            'Telefonní číslo:',
            'Ověřte',
            'Zadejte příjmení',
            'Zadejte jméno',
            'Введіть по батькові',
            'Vyberte typ',
            'Zadejte číslo',
            'Cestovní pas',
            'Zahraniční pas',
            'ID - karta',
            'Děkuji!',
            'Vaše žádost byla odeslána.',
            'Očekávejte telefonát operátora pro další spolupráci',
            'Potřebuji zdroje | Leleka – nadační fond'
        ],
        en: [
            'I need resources',
            'Personal data',
            'Last name',
            'First name',
            'Surname',
            'Document type',
            'Series and number',
            'Choose a type',
            'Phone number:',
            'Verify',
            'Enter the last name',
            'Enter the first name',
            'Enter the surname',
            'Choose a type',
            'Enter the number',
            'Passport',
            'Foreign passport',
            'ID - Card',
            'Thank you!',
            'Your application has been submitted.',
            'Expect a call from the operator for further cooperation',
            'I need resources | Leleka - charity fund'
        ],
        ua: [
            'Я потребую ресурси',
            'Персональні дані',
            'Прізвище',
            'Ім’я',
            'По батькові',
            'Тип документу',
            'Серія та номер',
            'Оберіть тип',
            'Номер телефону:',
            'Верифікувати',
            'Введіть прізвище',
            'Введіть ім’я',
            'Введіть по батькові',
            'Оберіть тип',
            'Введіть номер',
            'Паспорт',
            'Загран паспорт',
            'ID - Карта',
            'Дякую!',
            'Ваша заявка була відправлена.',
            'Очікуйте дзівнка від оператора для подальщой співдії',
            'Я потребую ресурси | Leleka - Благодійний фонд'
        ],
    },
    have_resources: {
        cz: [
            "Mám zdroje",
            'Jak vás kontaktovat?',
            'Telefonní číslo',
            'Vaše kontakty',
            'telefon, email, facebook',
            "Co je skladem?",
            'popište, jaké zdroje jsou k dispozici?',
            'Kde je k dispozici?',
            'prosím, uveďte, ve kterém městě jsou zdroje dostupné?',
            'Kategorie',
            'Jídlo',
            'Oblečení',
            'Léky',
            'Technické vybavení',
            'Doprava',
            'Dobrovolnictví',
            'Finanční pomoc',
            'Nabízím práci',
            'Jiný',
            'Dodávka',
            'Mohu přinést',
            'vlastní vyzvednutí',
            'Poznámky',
            "Souhlasím se zpracováním mých osobních údajů",
            "přečtěte si pravidla",
            'Hotovo, odeslat formulář',
            'Povinné pole',
            'Vyberte jednu nebo více kategorií',
            'Mám zdroje | Leleka – nadační fond',
            'Děkuji!',
            'Vaše žádost byla odeslána.',
            'Očekávejte telefonát operátora pro další spolupráci',

        ],
        en: [
            'I have resources',
            'What is your name?',
            'Phone number',
            'Your contacts',
            'phone, email, facebook',
            "What's in stock?",
            'describe what resources are available?',
            'Where is it available?',
            'please indicate in which city the resources are available?',
            'Category',
            'Food',
            'Clothing',
            'Medicines',
            'Technical equipment',
            'Transport',
            'Volunteering',
            'Financial assistance',
            'I offer a job',
            'Other',
            'Delivery',
            'I can bring',
            'self-pickup',
            'Notes',
            'I consent to the processing of my personal data',
            'read the rules',
            'Done, submit form',
            'Required field',
            'Select one or more categories',
            'I have resources | Leleka - charity fund',
            'Thank you!',
            'Your application has been submitted.',
            'Expect a call from the operator for further cooperation',
        ],
        ua: [
            'Маю ресурси',
            'Як до вас звертатися?',
            'Номер телефону',
            'Ваші контакти',
            'телефон, email, facebook',
            'Що є в наявності?',
            'опишіть які є в наявності ресурси?',
            'Де є в наявності?',
            'вкажіть в якому місті є в наявності ресурси?',
            'Категорія',
            'Продукти харчування',
            'Одяг',
            'Медикаменти',
            'Технічне устаткування',
            'Транспорт',
            'Волонтерство',
            'Фінансова допомога',
            'Пропоную роботу',
            'Iнше',
            'Доставка',
            'можу привезти',
            'самовивіз',
            'Нотатки',
            'даю згоду на обробку моїх персональних даних',
            'ознайомитися з правилами',
            'Готово, відправити форму',
            'Обов’язкове поле',
            'Оберіть одну або декілька категорій',
            'Маю ресурси | Leleka - Благодійний фонд',
            'Дякую!',
            'Ваша заявка була відправлена.',
            'Очікуйте дзівнка від оператора для подальщой співдії',
        ]
    },
    gdpr: {
        cz: [
            'Zásady ochrany osobních údajů v Mezinárodním nadačním fondu Leleka / nařízení GDPR',
            '1. Základní ustanovení',
            'Správcem osobních údajů podle čl. 4 bod 7 nařízení Evropského parlamentu a Rady (EU) 2016/679 o ochraně fyzických osob v souvislosti se zpracováním osobních údajů a o volném pohybu těchto údajů (dále jen: „GDPR”) je Mezinárodní nadační fond Leleka, se sídlem Hamerská 74/27, 360 01 Karlovy Vary, IČ 170 919 77, zapsaná v nadačním rejstříku u Krajského soudu v Plzni, oddíl N, vložka 378.(dále jen: „správce“).',
            'Kontaktní údaje správce jsou:',
            'adresa: Hamerská 74/27, 360 01 Karlovy Vary',
            'email: lelekafond@gmail.com ',
            'telefon: +420 778 500 911',
            'Správce jmenoval pověřence pro ochranu osobních údajů. Kontaktními údaji pověřence jsou: Denys Leonti, lelekafond@gmail.com',
            '2. Rozsah a zdroje zpracovávaných osobních údajů – odběratelé e-mailových zpravodajů',
            'Mezinárodní nadační fond Leleka zpracovává osobní údaje, které jí poskytli odběratelé e-mailových zpravodajů prostřednictvím formuláře registrace nebo jinou cestou, např. telefonicky, písemně. Zpracovávané osobní údaje tak mohou zahrnovat zejména:',
            'Osobní údaje běžné: jméno, e-mailová adresa a dále v souvislosti s elektronickým přístupem k webové stránce www.leleka.cz, soubory cookies a device identifikátor zařízení Odběratele e-mailových zpravodajů.',
            'Osobní údaje citlivé, resp. zvláštní kategorie (čl. 9 Nařízení): žádné.',
            'K seznamu odběratelů e-mailových zpravodajů mají přístup pouze pověření zaměstnanci Mezinárodního nadačního fondu Leleka.',
            'Mezinárodní nadační fond Leleka shromážděné údaje neposkytuje žádným třetím stranám, využívá je pouze pro potřeby rozesílky e-mailových zpravodajů.',
            'Odhlášení z odběru e-mailových zpravodajů je možné kdykoli, odhlašovací odkaz je v patičce každého e-mailu. ',
            '3. Rozsah a zdroje zpracovávaných osobních údajů –dárci Mezinárodního nadačního fondu Leleka',
            'Mezinárodní nadační fond Leleka zpracovává osobní údaje fyzických osob, které se rozhodly stát se dárci Mezinárodního nadačního fondu Leleka a to buď prostřednictvím systému leleka.cz či prostřednictvím uzavření darovací smlouvy. Zpracovávané osobní údaje o dárcích Mezinárodní nadační fond Leleka tak mohou zahrnovat zejména:',
            'Osobní údaje běžné: jméno, e-mailová adresa, adresa bydliště, telefon a informace o došlých platbách',
            'Osobní údaje citlivé, resp. zvláštní kategorie (čl. 9 Nařízení): žádné',
            'Osobní údaje dárců a informace o došlých platbách na účet Mezinárodního nadačního fondu Leleka zpracováváme primárně za účelem správného zaúčtování daru v systému a vystavení potvrzení o přijetí daru, které si mohou dárci uplatnit ve svém daňovém přiznání a snížit si tak základ daně z příjmu.',
            'Informace o dárcích a dárcovských transakcích vedeme také v dárcovské databázi. Osobní údaje využíváme k poděkování a informování o využití darovaných prostředků a k informování o činnosti Mezinárodního nadačního fondu Leleka. Toto zpracování provádíme na základě oprávněného zájmu v rámci adresného individuálního dárcovství. Údaje můžeme použít také k vytváření statistik a archivace pro případ sporů nebo reklamací.',
            ' 4. Rozsah a zdroje zpracovávaných osobních údajů – Příjemci podpory od Mezinárodního nadačního fondu Leleka',
            'Mezinárodní nadační fond Leleka zpracovává osobní údaje fyzických osob, které požádaly Mezinárodní nadační fond Leleka o podporu a ta jim byla poskytnuta na základě smlouvy o poskytnutí nadačního příspěvku Zpracovávané osobní údaje o příjemcích podpory od Mezinárodního nadačního fondu Leleka tak mohou zahrnovat zejména:',
            'Osobní údaje běžné: jméno, e-mailová adresa, adresa bydliště, telefon a číslo bankovního účtu',
            'Osobní údaje citlivé, resp. zvláštní kategorie (čl. 9 Nařízení): žádné',
            'Osobní údaje příjemců podpory od Mezinárodního nadačního fondu Leleka a informace o odeslaných platbách na účet příjemců zpracováváme primárně za účelem správného zaúčtování nadačních příspěvků v systému. Dále je zpracováváme pro účely vykazování poskytnuté podpory ve výroční zprávě Mezinárodního nadačního fondu Leleka, a to v souladu s povinnostmi, které nám ukládá Občanský zákoník a jeho ustanovení o fundacích.',
            'Informace o příjemcích podpory vedeme také v databázi poskytnutých grantů v systému. Osobní údaje využíváme k informování o grantových příležitostech a k informování o činnosti Mezinárodního nadačního fondu Leleka. Toto zpracování provádíme na základě oprávněného zájmu v rámci naší nadační činnosti. Údaje můžeme použít také k vytváření statistik a archivace pro případ sporů nebo reklamací. ',
            '5. Doba uchovávání údajů – odběratelé e-mailových zpravodajů',
            'Souhlas se zpracováním se uděluje na celé období, po které bude odběratel e-mailových zpravodajů mít zájem dostávat informace o činnosti Mezinárodního nadačního fondu Leleka. Období, pro které je souhlas udělen, končí odvoláním souhlasu.',
            'Osobní údaje budou zpracovány a uloženy po dobu, po kterou bude odběratel e-mailových zpravodajů mít zájem dostávat informace o činnosti Mezinárodního nadačního fondu Leleka. Poté Mezinárodní nadační fond Leleka uchová osobní údaje odběratele e-mailového zpravodaje ještě po dobu 5 let.',
            '6. Subjekty zpracovávající osobní údaje',
            'Osobní údaje zpracovává přímo Mezinárodní nadační fond Leleka, a to v písemné a elektronické formě. Osobní údaje mohou pro Mezinárodní nadační fond Leleka takto zpracovávat také další subjekty v postavení tzv. zpracovatelů, se kterými Mezinárodní nadační fond Leleka uzavře smlouvu o zpracování osobních údajů.',
            '7. Zpřístupnění údajů jiným osobám',
            'Osobní údaje dále mohou být zpřístupněny subjektům oprávněným dle zvláštních právních předpisů (např. orgánům činným v trestním řízení, apod.) a osobám v pozici zpracovatelů osobních údajů spolupracujících s Mezinárodním nadačním fondem Leleka.',
            '8. Vaše práva',
            'Za podmínek stanovených v nařízení GDPR máte:',
            '1. právo na přístup ke svým osobním údajům dle čl. 15 GDPR,',
            '2. právo opravu osobních údajů dle čl. 16 GDPR, popřípadě omezení zpracování dle čl. 18 GDPR,',
            '3. právo na výmaz osobních údajů dle čl. 17 GDPR,',
            '4. právo vznést námitku proti zpracování dle čl. 21 GDPR,',
            '5. právo na přenositelnost údajů dle čl. 20 GDPR,',
            '6. a právo odvolat souhlas se zpracováním písemně nebo elektronicky na adresu lelekafond@gmail.com',
            'Dále máte právo podat stížnost u Úřadu pro ochranu osobních údajů v případě, že se domníváte, že bylo porušeno Vaší právo na ochranu osobních údajů.',
            '9. Podmínky zabezpečení osobních údajů',
            'Správce prohlašuje, že přijal veškerá vhodná technická a organizační opatření k zabezpečení osobních údajů.',
            'Správce prohlašuje, že k osobním údajům mají přístup pouze jím pověřené osoby.',
            '10. Kódy třetích stran',
            'Na webových stránkách Mezinárodního nadačního fondu Leleka používáme kódy od společnosti Google, které nám pomáhají analyzovat chování návštěvníků webu. Detailní informace o Google Analytics a ochraně osobních údajů naleznete na http://www.google.com/intl/cs/privacy/privacy-policy.html. Pokud chcete zabránit sledování, můžete instalovat doplněk do vašeho webového prohlížeče (http://tools.google.com/dlpage/gaoptout).',
            'Tyto podmínky nabyly účinnosti dnem 01. 06. 2022.',
            'Pokud máte jakékoli dotazy nebo Vám je ve výše uvedených informacích něco nejasné, kontaktujte nás prosím na lelekafond@gmail.com, rádi odpovíme. Děkujeme.',
        ],
        en: [
            'Principles of personal data protection in the International Endowment Fund Leleka / GDPR Regulation',
            '1. Basic provisions',
            'The controller of personal data pursuant to Article 4 (7) of Regulation (EU) 2016/679 of the European Parliament and of the Council on the protection of individuals with regard to the processing of personal data and on the free movement of such data (hereinafter: "GDPR") is the Leleka with its registered office at Hamerská 74/27, 360 01 Karlovy Vary, IČ 170 919 77, entered in the Foundation Register at the Regional Court in Pilsen, Section N, Insert 378. (hereinafter referred to as the “Administrator”).',
            'The contact details of the administrator are:',
            'address: Hamerská 74/27, 360 01 Karlovy Vary',
            'email: lelekafond@gmail.com',
            'phone number: +420 778 500 911',
            'The administrator has appointed a data protection officer. The contact details of the commissioner are: Denys Leonti, lelekafond@gmail.com',
            '2. Scope and sources of processed personal data - subscribers of e-mail newsletters',
            'The Leleka International Endowment Fund processes personal data provided to it by subscribers of e-mail newsletters via the registration form or by other means, eg by telephone, in writing. The personal data processed may thus include in particular:',
            'Common personal data: name, e-mail address and in connection with electronic access to the website www.leleka.cz, cookies and device identifier of the e-mail newsletter subscriber\'s device.',
            'Personal data sensitive, resp. special category (Article 9 of the Regulation): none.',
            'Only authorized employees of the Leleka International Endowment Fund have access to the list of subscribers of e-mail newsletters.',
            'The Leleka International Endowment Fund does not provide the collected data to any third parties, it only uses it for the purpose of sending e-mail newsletters.',
            'You can unsubscribe from e-mail newsletters at any time, the unsubscribe link is in the footer of each e-mail.',
            '3. Scope and sources of processed personal data - donors of the International Endowment Fund Leleka',
            'The Leleka International Endowment Fund processes personal data of natural persons who have decided to become donors of the Leleka International Endowment Fund, either through the leleka.cz system or through the conclusion of a donation agreement. The processed personal data on donors to the Leleka International Endowment Fund may thus include in particular:',
            'Common personal data: name, e-mail address, address of residence, telephone and information on payments received',
            'Personal data sensitive, resp. special category (Article 9 of the Regulation): none',
            'We process donors\' personal data and information on payments received on behalf of the Leleka International Endowment Fund primarily for the purpose of correctly posting a gift in the system and issuing a gift receipt, which donors can use in their tax return to reduce their income tax base.',
            'We also keep information on donors and donor transactions in the donor database. We use personal data to thank and inform about the use of donated funds and to inform about the activities of the International Endowment Fund Leleka. We perform this processing on the basis of a legitimate interest within the framework of targeted individual donation. We can also use the data to create statistics and archive in case of disputes or complaints.',
            ' 4. Scope and sources of processed personal data - Recipients of support from the International Endowment Fund Leleka',
            'The Leleka International Endowment Fund processes personal data of natural persons who have applied for support from the Leleka International Endowment Fund and this has been provided to them on the basis of an endowment grant agreement.',
            'Common personal data: name, e-mail address, residential address, telephone number and bank account number',
            'Personal data sensitive, resp. special category (Article 9 of the Regulation): none',
            'We process the personal data of the beneficiaries from the Leleka International Endowment Fund and the information on the payments sent to the beneficiaries\' account primarily for the purpose of correctly posting the endowment contributions in the system. We also process them for the purpose of reporting the support provided in the annual report of the Leleka International Endowment Fund, in accordance with the obligations imposed on us by the Civil Code and its provisions on foundations.',
            'We also keep information on the beneficiaries in the database of provided grants in the system. We use personal data to inform about grant opportunities and to inform about the activities of the Leleka International Endowment Fund. We perform this processing on the basis of a legitimate interest within our foundation activities. We can also use the data to create statistics and archive in case of disputes or complaints.',
            '5. Data retention period - subscribers of e-mail newsletters',
            'Consent to the processing is granted for the entire period during which the subscriber of e-mail newsletters will be interested in receiving information about the activities of the International Endowment Fund Leleka. The period for which the consent is granted ends with the withdrawal of the consent.',
            'Personal data will be processed and stored for the period during which the subscriber of e-mail newsletters will be interested in receiving information about the activities of the International Endowment Fund Leleka. After that, the Leleka International Endowment Fund will keep the personal data of the e-mail newsletter subscriber for another 5 years.',
            '6. Entities processing personal data',
            'Personal data is processed directly by the International Endowment Fund Leleka, in written and electronic form. Personal entities may also process personal data for the Leleka International Endowment Fund in the position of so-called processors, with whom the Leleka International Endowment Fund will conclude an agreement on the processing of personal data.',
            '7. Disclosure of data to other persons',
            'Personal data may also be made available to entities authorized under special legal regulations (eg bodies active in criminal proceedings, etc.) and persons in the position of processors of personal data cooperating with the Leleka International Endowment Fund.',
            '8. Your rights',
            'Under the conditions set out in the GDPR Regulation, you have:',
            '1. the right of access to their personal data pursuant to Article 15 of the GDPR,',
            '2. the right to correct personal data pursuant to Article 16 of the GDPR, or restrictions on processing pursuant to Article 18 of the GDPR,',
            '3. the right to delete personal data pursuant to Article 17 of the GDPR,',
            '4. the right to object to the processing pursuant to Article 21 of the GDPR,',
            '5. the right to data portability according to Article 20 of the GDPR,',
            '6. and the right to withdraw consent to processing in writing or electronically to lelekafond@gmail.com',
            'You also have the right to file a complaint with the Office for Personal Data Protection if you believe that your right to personal data protection has been violated.',
            '9. Terms of personal data security',
            'The controller declares that it has taken all appropriate technical and organizational measures to secure personal data.',
            'The controller declares that only persons authorized by him have access to personal data.',
            '10. Third party codes',
            'On the Leleka International Endowment Fund website, we use codes from Google to help us analyze the behavior of website visitors. Detailed information about Google Analytics and privacy can be found at http://www.google.com/intl/en/privacy/privacy-policy.html. To prevent tracking, you can install the add-on in your web browser (http://tools.google.com/dlpage/gaoptout).',
            'These conditions came into force on June 1, 2022.',
            'If you have any questions or something is unclear to you in the above information, please contact us at lelekafond@gmail.com, we will be happy to answer. Thank you.',
        ],
        ua: [
            'Принципи захисту персональних даних у Міжнародному благодійному фонді Leleka / регламент GDPR',
            '1. Основні положення',
            'Розпорядник персональних даних відповідно до статті 4 (7) Регламенту (ЄС) 2016/679 Європейського Парламенту та Ради про захист фізичних осіб щодо обробки персональних даних та про вільний рух таких даних (далі: «GDPR») — це Leleka із зареєстрованим офісом за адресою Hamerská 74/27, 360 01 Karlovy Vary, IČ 170 919 77, внесена до Реєстру Фондів при обласному суді м. Пльзень, розділ N, вставка 378. (далі іменується як «Адміністратор»).',
            'Контактні дані адміністратора:',
            'адреса: Hamerská 74/27, 360 01 Карлові Вари',
            'електронна адреса: lelekafond@gmail.com',
            'номер телефону: +420 778 500 911',
            'Адміністратор призначив спеціаліста із захисту даних. Контактні дані уповноваженого: Денис Леонті, lelekafond@gmail.com',
            '2. Обсяг та джерела оброблюваних персональних даних - передплатники розсилок електронної пошти',
            'Міжнародний благодійний фонд «Лелека» обробляє персональні дані, надані йому передплатниками розсилок електронною поштою через реєстраційну форму або іншим способом, наприклад, по телефону, у письмовій формі. Таким чином, оброблені персональні дані можуть включати, зокрема:',
            'Загальні персональні дані: ім’я, адреса електронної пошти та у зв’язку з електронним доступом до веб-сайту www.leleka.cz, файли cookie та ідентифікатор пристрою абонента розсилки електронної пошти.',
            'Конфіденційні дані, відповідно. спеціальна категорія (ст. 9 Положення): немає.',
            'Доступ до списку передплатників розсилок електронної пошти мають лише уповноважені працівники Міжнародного благодійного фонду «Лелека».',
            'Міжнародний благодійний фонд «Лелека» не надає зібрані дані третім особам, він використовує їх лише з метою розсилки інформаційних бюлетенів електронною поштою.',
            'Ви можете скасувати підписку на розсилку електронної пошти в будь-який час, посилання для скасування підписки знаходиться в нижньому колонтитулі кожного листа.',
            '3. Обсяг та джерела оброблених персональних даних – донори Міжнародного благодійного фонду Leleka',
            'Міжнародний благодійний фонд «Лелека» обробляє персональні дані фізичних осіб, які вирішили стати донорами Міжнародного благодійного фонду «Лелека», або через систему leleka.cz, або шляхом укладення договору про пожертвування. Таким чином, оброблені персональні дані про донорів Міжнародного благодійного фонду «Лелека» можуть включати, зокрема:',
            'Загальні персональні дані: ім\'я, адреса електронної пошти, адреса проживання, телефон та інформація про отримані платежі',
            'Конфіденційні дані, відповідно. спеціальна категорія (ст. 9 Положення): немає',
            'Ми обробляємо персональні дані донорів та інформацію про виплати, отримані від імені Міжнародного благодійного фонду «Лелека», в першу чергу з метою коректного розміщення подарунка в системі та видачі подарункового чека, який донори можуть використовувати у своїй податковій декларації для зменшення податку на прибуток. бази.',
            'Ми також зберігаємо інформацію про донорів та транзакції донорів у базі даних донорів. Ми використовуємо персональні дані, щоб подякувати та інформувати про використання пожертвуваних коштів та інформувати про діяльність Міжнародного благодійного фонду Leleka. Ми виконуємо цю обробку на основі законного інтересу в рамках цільового індивідуального пожертвування. Ми також можемо використовувати дані для створення статистики та архівування на випадок суперечок чи скарг.',
            ' 4. Обсяг та джерела оброблюваних персональних даних – одержувачі підтримки від Міжнародного благодійного фонду Leleka',
            'Міжнародний благодійний фонд «Лелека» обробляє персональні дані фізичних осіб, які звернулися за підтримкою до Міжнародного благодійного фонду «Лелека», надані їм на підставі договору про надання допомоги.',
            'Загальні персональні дані: ім’я, адреса електронної пошти, адреса проживання, номер телефону та номер банківського рахунку',
            'Конфіденційні дані, відповідно. спеціальна категорія (ст. 9 Положення): немає',
            'Ми обробляємо персональні дані бенефіціарів від Міжнародного благодійного фонду «Лелека» та інформацію про виплати, що надсилаються на рахунок бенефіціарів, в першу чергу з метою коректного розміщення внесків у системі. Ми також обробляємо їх з метою звітності про підтримку, надану в річному звіті Міжнародного благодійного фонду «Лелека», відповідно до зобов’язань, покладених на нас Цивільним кодексом та його положеннями про фонди.',
            'Також ми зберігаємо інформацію про бенефіціарів у базі даних наданих грантів у системі. Ми використовуємо персональні дані, щоб інформувати про можливості надання грантів та інформувати про діяльність Міжнародного благодійного фонду Leleka. Ми виконуємо цю обробку на основі законного інтересу в рамках діяльності нашого фонду. Ми також можемо використовувати дані для створення статистики та архівування на випадок суперечок чи скарг.',
            '5. Період збереження даних - передплатники розсилок електронної пошти',
            'Згода на обробку надається на весь період, протягом якого передплатник розсилок електронною поштою буде зацікавлений в отриманні інформації про діяльність Міжнародного благодійного фонду Leleka. Термін, на який надається згода, закінчується відкликанням згоди.',
            'Персональні дані оброблятимуться та зберігатимуться протягом періоду, протягом якого передплатник розсилок електронною поштою буде зацікавлений в отриманні інформації про діяльність Міжнародного благодійного фонду Leleka. Після цього Міжнародний благодійний фонд «Лелека» зберігатиме персональні дані передплатника електронної розсилки ще 5 років.',
            '6. Суб’єкти, які обробляють персональні дані',
            'Персональні дані обробляються безпосередньо Міжнародним благодійним фондом Leleka в письмовій та електронній формі. Особи-фізичні особи можуть також обробляти персональні дані для Міжнародного благодійного фонду «Лелека» на посаді так званих обробників, з якими Міжнародний благодійний фонд «Лелека» укладе договір про обробку персональних даних.',
            '7. Розкриття даних іншим особам',
            'Персональні дані також можуть бути доступні суб’єктам, уповноваженим відповідно до спеціальних правових норм (наприклад, органам, які займаються кримінальним судочинством тощо), та особам, які займають посаду обробників персональних даних, які співпрацюють з Міжнародним благодійним фондом Leleka.',
            '8. Ваші права',
            'Відповідно до умов, викладених у Регламенті GDPR, ви маєте:',
            '1. право на доступ до своїх персональних даних відповідно до статті 15 GDPR,',
            '2. право на виправлення персональних даних відповідно до статті 16 GDPR або обмеження обробки відповідно до статті 18 GDPR,',
            '3. право на видалення персональних даних відповідно до статті 17 GDPR,',
            '4. право заперечувати проти обробки відповідно до статті 21 GDPR,',
            '5. право на перенесення даних відповідно до статті 20 GDPR,',
            '6. і право відкликати згоду на обробку в письмовій або електронній формі на адресу lelekafond@gmail.com.',
            'Ви також маєте право подати скаргу до Управління захисту персональних даних, якщо вважаєте, що ваше право на захист персональних даних було порушено.',
            '9. Умови захисту персональних даних',
            'Контролер заявляє, що вжив усіх належних технічних та організаційних заходів для захисту персональних даних.',
            'Контролер заявляє, що доступ до персональних даних мають лише уповноважені ним особи.',
            '10. Коди третіх сторін',
            'На веб-сайті Міжнародного благодійного фонду Leleka ми використовуємо коди від Google, щоб допомогти нам аналізувати поведінку відвідувачів веб-сайту. Детальну інформацію про Google Analytics і конфіденційність можна знайти на веб-сторінці http://www.google.com/intl/en/privacy/privacy-policy.html. Щоб запобігти відстеженню, ви можете встановити доповнення у своєму веб-переглядачі (http://tools.google.com/dlpage/gaoptout).',
            'Ці умови набрали чинності з 1 червня 2022 року.',
            'Якщо у вас виникли запитання або вам щось незрозуміло у наведеній вище інформації, будь ласка, зв’яжіться з нами за адресою lelekafond@gmail.com, ми будемо раді відповісти. Дякую.',
        ]
    }
}