export const langs = {
    main: {
        cz: [
            'Přispějte',
            'Leleka – nadační fond',
            'Každý má svou frontu ',
            'KDO MY JSME',
            'Mezinárodní nadační fond Leleka byl založen Ukrajinci z Karlových Varů a jeho cílem je pomáhat těm, kteří chrání Ukrajinu před agresorem, stejně jako těm, kteří byli nuceni se přestěhovat do Česka.',
            'Válka přišla na Ukrajinu iž v roce 2014, kdy první ruští vojáci a žoldáci obsadili města našeho rodného Donbasu. Ne z televizních zpráv a internetu jsme se museli dozvědět, co se dělo v Doněcku, protože jsme viděli všechno na vlastní oči. Po přestěhování do České republiky jsme svými silami pokračovali v pomoci našim bojovníkům v zóně OSS. Od 24. února začala naše skupina jednat koordinovaněji. Za dva měsíce jsme byli schopni poskytnout mnoha vojákům Ozbrojených sil Ukrajiny a dobrovolníkům lékárničky, neprůstřelné vesty a další předměty individuální ochrany. Do nemocnic Dněpra a Charkova byly převezeny potřebné léky. ',
            'A pak přišel čas založit nadační fond, který by spojil úsilí mnoha lidí a organizací. Musime se sjednotit kvůli vítězství, aby na Ukrajině znovu zavládl mír.',
            'Chceš pomocí',
            'Jsi člověk, nebo organizace, která má humanitární a lékařské zdroje',
            'Potřebuješ pomoc',
            'Jsi člověk, nebo organizace, která potřebuje humanitární a lékařské zdroje',
            'Naše činnost',
            '1. Nakupujeme po celé Evropě a posíláme na Ukrajnu všechno, co je nezbytné nutné pro naše obránce:',
            'deficitné optické vybavení, zejména termovize, přístrojе nočního vidění a další',
            'léky a zdravotnické prostředky první potřeby při zraněních',
            'osobní ochranné prostředky (záchranné neprůstřelné vesty, chrániče kolen, brýle a sluchátka), lékárničky a vojenské oblečení ',
            '2. Pomáháme nuceným přistěhovalcům z Ukrajiny do Česka: ',
            's ubytováním a integraci',
            's umístěním dětí do sportovních sekcí ',
            's organizací dětského volného času ',
            'humanitární pomocí (věci, obuv, nádobí, nábytek a zařízení do bytů, dětské kočárky, hráčky atd.) spolu se spolkem Nádech z.s. v Karlových Varech',
            'Více detailní informací na našich sociálních sítích',
            'Finanční pomoc na sběr zdrojů',
            'Za finanční dary Leleka nakupuje dostupné zdroje a dodává Ukrajincům podle potřeby',
            'Rekvizity',
            'Sledujte nejnovější zprávy:'
        ],
        en: [
            'Donate',
            'Leleka - charity fund',
            'Everyone fights on their own front',
            'WHO WE ARE',
            'Charity fund “Leleka” is founded by Ukrainians from Karlovy Vary, and is intended to help those who defend Ukraine from the aggressor and those who were forced to move to Czech Republic.',
            'The war came to our homeland in 2014, when first Russian soldiers and mercenaries invaded cities of our home Donbas region. We had to find out everything that happened in Donetsk not from the television news or the internet - we have seen everything firsthand. Already living in Czech Republic we continued to help our military in the Joint Forces Operation zone. Since 24 of February our group began to make more coordinated actions. In two months we succeeded in providing many of the soldiers from the Armed Forces of Ukraine and volunteers with medical packs, bulletproof vests and other personal protection equipment. Hospitals in Dnipro and Kharkiv were supplied with necessary medicine.',
            'Now it is time to launch a charity fund to unite the efforts of many people and organisations. To unite for the victory, to bring peace to Ukraine. ',
            'I want to help ',
            'You are the person or organisation that has in stock humanitarian and medical resources.',
            'I need help',
            'You are the person or organisation that needs humanitarian and medical resources. ',
            'WHAT DO WE DO?',
            '1. We buy everything that our defenders need throughout all Europe and send to Ukraine:',
            'scarce optical equipment such as thermal imagers, night-vision devices, etc; ',
            'medicine and essential medical supplies for injury;',
            'personal protection equipment (bulletproof vests, knee pads, military goggles and headphones), medical packs and military fatigues;',
            'We help Ukrainian refugees in Czech Republic:',
            'with accommodation;',
            'with enrolling children in sports clubs;',
            'organisation of children’s activities;',
            'humanitarian help (clothes, shoes, etc);',
            'More detailed information is in our social media',
            'Financial assistance for collection of the resources',
            'For the money transferred Leleka buys available resources and supply to Ukrainians when needed',
            'Bank transfer details',
            'Follow the latest news:'
        ],
        ua: [
            'Допомогти',
            'Leleka - Благодійний фонд',
            'У кожного свій фронт',
            'Хто ми',
            'Благодійний фонд "Лелека" заснований українцями з Карлових Вар і має на меті допомагати тим, хто захищає Україну від агресора, а також тим, хто були вимушені переїхати до Чехії.',
            'Війна прийшла в наш дім ще 2014 року, коли перші російські військові та найманці захопили міста нашого рідного Донбасу. Не з телевізійних новин та інтернету нам довелося дізнатися, що відбувалося в Донецьку, адже бачили все на власні очі. Вже живучи у Чехії, ми своїми силами продовжували допомагати нашим бійцям в зоні ООС. З 24 лютого наша група почала діяти більш скоординовано. За 2 місяці ми змогли забезпечити багатьох військових ЗСУ і добровольців аптечками, бронежилетами та іншими предметами індивідуального захисту. До шпиталів Дніпра та Харкова були передані необхідні ліки.',
            'Настав час створити благодійний фонд, аби об\'єднати зусилля багатьох людей і організацій. Об\'єднати заради перемоги, заради того, аби в Україні знову запанував мир.',
            'Хочу допомогти',
            'Ти людина, чи організація яка і має в наявності гуманітарні та медичні ресурси.',
            'Необхідна допомога',
            'Ти людина, чи організація якій необхідна гуманітарні та медичні ресурси.',
            'Що ми робимо',
            '1. Закуповуємо по всій Європі та відправляємо в Україну все те, що так необхідне нашим захисникам:',
            'дефіцитне оптичне обладнання, таке як тепловізори, прибори нічного бачення тощо',
            'ліки та медичні засоби першої необхідності при пораненнях',
            'засоби індивідуального захисту (бронежилети, наколінники, окуляри та навушники), аптечки та військовий одяг',
            '2. Допомагаємо вимушеним переселенцям з України до Чехії:',
            'з поселенням',
            'з влаштуванням дітей до спортивних секцій',
            'з організацією дитячого дозвілля',
            'гуманітарною допомогою (речі, взуття тощо)',
            'Більше детальної інформації у наших соціальних мережах',
            'Фінансова допомога на збір ресурсів',
            'За переказані кошти Leleka закуповує доступні ресурси та постачає українцям у потребі.',
            'Реквізити',
            'Слідкуйте за останніми новинами:'
        ]
    },
    transfer: {
        cz: [
            'Informace pro fyzické osoby',
            'Vážení, nepochybujte o tom, že každý váš příspěvek do fondu výrazně pomůže naší společné velké věci! Především vaše podpora znamená boj za mír, demokracii a solidaritu a hlavně mír pro Ukrajinu a celý civilizovaný svět. Každý z nás může hodně, ale společně můžeme všechno!',
            'Informace pro právnické osoby',
            'Vážení podnikatelé, každý váš finanční příspěvek pomůže těm, kteří potřebují pomoc a podporu, kteří stojí za ochranou míru a demokracie v Evropě a jsou garanty naší svobodné budoucnosti. Za charitativní finanční výlohy české legislativy počítá s daňovými úlevami. Pro sponzorské společnosti máme připravenou smlouvu, která je stanovena zákonem při charitativním příspěvku na konkrétní účelovou pomoc. Podporováním naší charitativní nadace podporujete naši svobodu!',
            'Rekvizity | Leleka – nadační fond'
        ],
        en: [
            'Information for Natural persons',
            'Be sure that each of your contribution to the fund will help a lot in our common great goal! First of all, your support means the fight for peace, democracy and solidarity, and above all - peace for Ukraine and all civilised world. Everyone can do a lot, but together we can do everything!',
            'Information for Juridical persons ',
            'Dear entrepreneurs, each of your financial contributions will help those who need assistance and support, those who stand up for peace and democracy in Europe and are the guarantees of our free future. For the charitable financial contributions due to the Czech legislation there are tax benefits. For the company-sponsor we have prepared an agreement  provided by law when making a charitable contribution for the specific targeted assistance. By supporting our charity fund you support our freedom!',
            'Bank transfer details | Leleka - charity fund'
        ],
        ua: [
            'Інформація для фізичних осіб',
            'Шановні, не майте сумнiв, що кожний ваш посильний внесок у фонд, значно допоможе нашiй спiльнiй великiй справi! Насамперед , ваша пiдтримка означає боротьбу за мир, демократiю i солiдарнiсть, та головне - мир для Украïни та всього цивiлiзованого світу. Кожен із нас може багато, але разом ми можемо все!',
            'Інформація для підприємств',
            'Шановні підприємці, кожен ваш фінансовий внесок допоможе тим, хто потребує допомоги та підтримки, хто стоїть на захисті миру та демократії в Європі та є гарантами нашого вільного майбутнього. За благодійні фінансові винесення Чеським законодавством передбачено податкові пільги. Для компаній-спонсорів у нас підготовлений договір, який передбачений законом при внесенні благодійного внеску на конкретну цільову допомогу. Підтримуючи наш благодійний фонд, ви підтримуєте нашу свободу!',
            'Реквізити | Leleka - Благодійний фонд'
        ],
    },
    need_resources: {
        cz: [
            'Potřebuji zdroje',
            'Osobní data',
            'Příjmení',
            'Jméno',
            'По батькові',
            'Typ průkazů',
            'Číslo průkazů',
            'Vyberte typ',
            'Telefonní číslo:',
            'Ověřte',
            'Zadejte příjmení',
            'Zadejte jméno',
            'Введіть по батькові',
            'Vyberte typ',
            'Zadejte číslo',
            'Cestovní pas',
            'Zahraniční pas',
            'ID - karta',
            'Děkuji!',
            'Vaše žádost byla odeslána.',
            'Očekávejte telefonát operátora pro další spolupráci',
            'Potřebuji zdroje | Leleka – nadační fond'
        ],
        en: [
            'I need resources',
            'Personal data',
            'Last name',
            'First name',
            'Surname',
            'Document type',
            'Series and number',
            'Choose a type',
            'Phone number:',
            'Verify',
            'Enter the last name',
            'Enter the first name',
            'Enter the surname',
            'Choose a type',
            'Enter the number',
            'Passport',
            'Foreign passport',
            'ID - Card',
            'Thank you!',
            'Your application has been submitted.',
            'Expect a call from the operator for further cooperation',
            'I need resources | Leleka - charity fund'
        ],
        ua: [
            'Я потребую ресурси',
            'Персональні дані',
            'Прізвище',
            'Ім’я',
            'По батькові',
            'Тип документу',
            'Серія та номер',
            'Оберіть тип',
            'Номер телефону:',
            'Верифікувати',
            'Введіть прізвище',
            'Введіть ім’я',
            'Введіть по батькові',
            'Оберіть тип',
            'Введіть номер',
            'Паспорт',
            'Загран паспорт',
            'ID - Карта',
            'Дякую!',
            'Ваша заявка була відправлена.',
            'Очікуйте дзівнка від оператора для подальщой співдії',
            'Я потребую ресурси | Leleka - Благодійний фонд'
        ],
    },
    have_resources: {
        cz: [
            "Mám zdroje",
            'Jak vás kontaktovat?',
            'Telefonní číslo',
            'Vaše kontakty',
            'telefon, email, facebook',
            "Co je skladem?",
            'popište, jaké zdroje jsou k dispozici?',
            'Kde je k dispozici?',
            'prosím, uveďte, ve kterém městě jsou zdroje dostupné?',
            'Kategorie',
            'Jídlo',
            'Oblečení',
            'Léky',
            'Technické vybavení',
            'Doprava',
            'Dobrovolnictví',
            'Finanční pomoc',
            'Nabízím práci',
            'Jiný',
            'Dodávka',
            'Mohu přinést',
            'vlastní vyzvednutí',
            'Poznámky',
            "Souhlasím se zpracováním mých osobních údajů",
            "přečtěte si pravidla",
            'Hotovo, odeslat formulář',
            'Povinné pole',
            'Vyberte jednu nebo více kategorií',
            'Mám zdroje | Leleka – nadační fond',
            'Děkuji!',
            'Vaše žádost byla odeslána.',
            'Očekávejte telefonát operátora pro další spolupráci',

        ],
        en: [
            'I have resources',
            'What is your name?',
            'Phone number',
            'Your contacts',
            'phone, email, facebook',
            "What's in stock?",
            'describe what resources are available?',
            'Where is it available?',
            'please indicate in which city the resources are available?',
            'Category',
            'Food',
            'Clothing',
            'Medicines',
            'Technical equipment',
            'Transport',
            'Volunteering',
            'Financial assistance',
            'I offer a job',
            'Other',
            'Delivery',
            'I can bring',
            'self-pickup',
            'Notes',
            'I consent to the processing of my personal data',
            'read the rules',
            'Done, submit form',
            'Required field',
            'Select one or more categories',
            'I have resources | Leleka - charity fund',
            'Thank you!',
            'Your application has been submitted.',
            'Expect a call from the operator for further cooperation',
        ],
        ua: [
            'Маю ресурси',
            'Як до вас звертатися?',
            'Номер телефону',
            'Ваші контакти',
            'телефон, email, facebook',
            'Що є в наявності?',
            'опишіть які є в наявності ресурси?',
            'Де є в наявності?',
            'вкажіть в якому місті є в наявності ресурси?',
            'Категорія',
            'Продукти харчування',
            'Одяг',
            'Медикаменти',
            'Технічне устаткування',
            'Транспорт',
            'Волонтерство',
            'Фінансова допомога',
            'Пропоную роботу',
            'Iнше',
            'Доставка',
            'можу привезти',
            'самовивіз',
            'Нотатки',
            'даю згоду на обробку моїх персональних даних',
            'ознайомитися з правилами',
            'Готово, відправити форму',
            'Обов’язкове поле',
            'Оберіть одну або декілька категорій',
            'Маю ресурси | Leleka - Благодійний фонд',
            'Дякую!',
            'Ваша заявка була відправлена.',
            'Очікуйте дзівнка від оператора для подальщой співдії',
        ]
    }
}